[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "xmlutils"
    version = "@project.version@"
    path = "../xmlutils-native/build/libs/xmlutils-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["xmlutils"]
