[package]
org = "ballerina"
name = "xmlutils"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../xmlutils-native/build/libs/xmlutils-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "xmlutils"
version = "@project.version@"
