[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "xmlutils"
    version = "1.0.0-SNAPSHOT"
    path = "../xmlutils-native/build/libs/xmlutils-native-1.0.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["xmlutils"]
